name: Bundle

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed
  
  pull_request:
    branches: [main]
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Bundle
        run: |
          npm install
          npm run bundle

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: bin/downloader.zip
          retention-days: 7
